config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    get "trips/upcoming", to: "trips#upcoming", as: "upcoming_trips"
    get "trips/favorites", to: "trips#favorites", as: "favorite_trips"
    resources :trips, only: [:index, :show]
  end

  resources :trips, except: [:index, :show]
  put "trips/:id/update_favorite_status", to: "trips#update_favorite_status", as: "update_favorite"

  resources :supplies

  put "trip_supplies/:id/increase", to: "trip_supplies#increase", as: "trip_supplies_increase"
  put "trip_supplies/:id/decrease", to: "trip_supplies#decrease", as: "trip_supplies_decrease"

  post "trips/results"

  authenticated :user do
    root "users#show", :as => :authenticated_root
  end
  root "landing#index"
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  has_many :trip_supplies
  has_many :trips, :through => :trip_supplies

  validates :name, :presence => true
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :trip_supplies
  has_many :supplies, :through => :trip_supplies

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true
  validate :end_after_start
  validates :start_date, :presence => true
  validates :end_date, :presence => true

  accepts_nested_attributes_for :supplies

  def self.upcoming
    Trip.where(:start_date => Date.today..(Date.today + 1.months))
  end

  def start_date_formatter
    self.start_date.strftime("%B %d, %Y")
  end

  def end_date_formatter
    self.end_date.strftime("%B %d, %Y")
  end

  private
    def end_after_start
      return if end_date.blank? || start_date.blank?

      if end_date < start_date
        errors.add(:end_date, "must be after the start date")
      end
    end

end

app/models/trip_supply.rb
class TripSupply < ActiveRecord::Base
  belongs_to :trip
  belongs_to :supply

  def increase_quantity
    self.quantity += 1
  end

  def decrease_quantity
    self.quantity -= 1
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable

  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, presence: true, on: :create

  has_many :trips
  has_many :supplies, :through => :trips

  def self.from_omniauth(auth_hash)
    where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create do |user|
      user.provider = auth_hash.provider
      user.uid = auth_hash.uid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect(user)
    else
      flash.error = "Your Twitter credentials are incorrect"
      redirect_to new_user_registration_path
    end
  end

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController

  def index
    @trip = Trip.find(params[:trip_id])
    @supplies = @trip.supplies
  end

  private

  def supply_params
    params.require(:supply).permit(:name)
  end
end

app/controllers/trip_supplies_controller.rb
class TripSuppliesController < ApplicationController

  def increase
    trip_supply = TripSupply.find(params[:id])
    trip = Trip.find(trip_supply.trip_id)
    trip_supply.increase_quantity
    trip_supply.save
    redirect_to user_trip_path(current_user, trip)
  end

  def decrease
    trip_supply = TripSupply.find(params[:id])
    trip = Trip.find(trip_supply.trip_id)
    trip_supply.decrease_quantity
    trip_supply.save
    redirect_to user_trip_path(current_user, trip)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = current_user.trips
    respond_to do |format|
      format.html { render :index }
      format.json { render :json => @trips }
    end
  end

  def upcoming
    @trips = current_user.trips.upcoming
    render :json => @trips
  end

  def description
    trip = Trip.find(params[:id])
    render :plain => trip.description
  end

  def favorites
    @fav_trips = Trip.where(user_id: current_user.id, favorite: true)
  end

  def results
    response = Faraday.get do |req|
      req.url "http://api.amp.active.com/camping/campgrounds/?"
      req.params['api_key'] = Rails.application.secrets.active_api_key
      req.params['pname'] = params["pname"]
    end
    @json = JSON.parse(Hash.from_xml(response.body).to_json)
    if @json["resultset"]["count"] == "0"
      flash[:error] = "Park not found"
      redirect_to root_path
    end
  end

  def new
    @trip = Trip.new
    @name = params[:name]
    response = Faraday.get do |req|
      req.url "http://api.amp.active.com/camping/campground/details?"
      req.params['api_key'] = Rails.application.secrets.active_api_key
      req.params['contractCode'] = params[:contract_code]
      req.params['parkId'] = params[:park_id]
    end
    json = JSON.parse(Hash.from_xml(response.body).to_json)
    @description = json["detailDescription"]["description"]
  end

  def create
    @trip = current_user.trips.create(trip_params)
    if @trip.save
      flash[:notice] = "Trip Saved"
      redirect_to user_trip_path(current_user, @trip)
    else
      render 'new'
    end
  end

  def show
    @trip = Trip.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render :json => @trip}
    end
  end

  def update
    @trip = Trip.find(params[:id])
    @trip.update(trip_params)
    if @trip.save
      render 'supplies/show', :layout => false
    else
      flash[:error] = @errors
      redirect_to user_trip_path(current_user, @trip)
    end
  end

  def update_favorite_status
    trip = Trip.find(params[:id])
    trip.favorite = !trip.favorite
    trip.save
    redirect_to user_trip_path(current_user, trip)
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :description, :favorite, :start_date, :end_date, :user_id, :supplies_attributes => [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="landing-content">
  <div class="landing-text">
    <h1>Welcome to Camp Hunt</h1>
    <h2>Find Your Next Adventure Here</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampHunt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav nav-text">
        <li><%= link_to "Camp Hunt", root_path %></li>
        <% if current_user %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "My Trips", user_trips_path(current_user) %></li>
          <li><%= link_to "My Favorites", user_favorite_trips_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In With Twitter", user_twitter_omniauth_authorize_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>
<%= yield %>

</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/supplies/index.html.erb
<h1>Supplies for Your <%= @trip.name %> Trip</h1>
<% @supplies.each do |supply| %>
  <%= supply.name %>
<% end %>

app/views/supplies/show.html.erb
<%= Supply.find(@trip.trip_supplies.last.supply_id).name %>
<%= @trip.trip_supplies.last.quantity %>
<%= @trip.trip_supplies.last.id %>

app/views/trips/favorites.html.erb
<div class="container col-md-12">
  <h1>All Your Favorite Trips</h1>
  <div class="col-md-6">
      <table class="table table-striped">
        <tr>
          <th>Trip Name</th>
          <th>Start Date</th>
          <th>End Date</th>
        </tr>
        <% @fav_trips.each do |trip| %>
          <tr>
            <td><%= link_to "#{trip.name}", user_trip_path(current_user, trip) %></td>
            <td><%= trip.start_date_formatter %></td>
            <td><%= trip.end_date_formatter %></td>
          </tr>
        <% end %>
      </table>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container col-md-12">
  <h1>All Your Trips</h1>
  <% @trips.each do |trip| %>
    <h3><%= link_to "#{trip.name}", user_trip_path(current_user, trip) %></h3>
    <div id="trip-<%= trip.id %>"><%= truncate(trip.description) %></div>
    <button class="js-more" data-trip="<%= trip.id %>" data-user="<%= trip.user_id %>">Read More</button>
    <ul id="trip_<%= trip.id %>_supplies"></ul>
  <% end %>
</div>

app/views/trips/new.html.erb
<div class="container">
  <% if @name %>
    <h2>Lets get ready for your trip to <%= @name %></h2>
  <% else %>
    <h2>Lets get ready for your trip!</h2>
  <% end %>

<%= form_for @trip do |f| %>
  <div class="fields_with_errors">
    <% if @trip.errors.any? %>
      <div>
        <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>
        <ul>
          <% @trip.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
  <%= f.label "Name" %><br>
  <%= f.text_field :name, value: @name, class: "form-control" %><br>
  <%= f.label "Description" %><br>
  <%= f.text_area :description, value: @description, rows: "5", class: "form-control" %><br>
  <%= f.label "Start Date" %><br>
  <%= f.date_field :start_date, class: "form-control" %><br>
  <%= f.label "End Date" %><br>
  <%= f.date_field :end_date, class: "form-control" %><br>
  <%= f.fields_for :supplies, @trip.supplies.build do |supplies_fields| %><br>
    <%= supplies_fields.label "Supply Name" %><br>
    <%= supplies_fields.text_field :name %><br><br>
  <% end %>
  <%= f.submit %>
<% end %>
</div>

app/views/trips/results.html.erb
<h1>Here are your results for <%= @json["resultset"]["pname"].titlecase %></h1>

<table class="table table-striped">
  <% if @json["resultset"]["result"].is_a?(Array) %>
    <% @json["resultset"]["result"].each do |park| %>
      <tr>
        <td>
          <%= park["facilityName"].titlecase %></br>
          <button><%= link_to "Create Trip",
            new_trip_path(name: "#{park["facilityName"].titlecase}",
                               contract_code: "#{park["contractID"]}",
                               park_id: "#{park["facilityID"]}") %>
        </button>
        </td>
      </tr>
    <% end %>
  <% else %>
      <tr>
        <td>
          <%= @json["resultset"]["result"]["facilityName"].titlecase %><br>
          <button><%= link_to "Create Trip",
          new_trip_path(name: @json["resultset"]["result"]["facilityName"].titlecase,
                        contract_code: @json["resultset"]["result"]["contractID"],
                        park_id: @json["resultset"]["result"]["facilityID"]) %>
        </button>
        </td>
      </tr>
  <% end %>
</table>

app/views/trips/show.html.erb
<div class="container col-md-12">
  <h2>Lets get ready for your trip to <%= @trip.name %></h2>
  <p><%= @trip.description %></p>
    <% if @trip.favorite == true %>
      <%= button_to "Remove From Favorites",
        update_favorite_path(@trip),
        class: "btn btn-danger",
        method: :put %>
    <% else %>
      <%= button_to "Add To Favorites",
        update_favorite_path(@trip),
        class: "btn btn-primary",
        method: :put %>
    <% end %>
</div>

<div class="container col-md-12">
<h3>Supplies</h3>
    <table class="table">
      <% @trip.trip_supplies.each do |supply| %>
        <tr>
          <td><%= Supply.find(supply.supply_id).name %>
          <%= supply.quantity %>
          <div style="display:inline-block;">
            <%= button_to "+1", trip_supplies_increase_path(supply), :class => "quantity", method: :put %>
          </div>
          <div style="display:inline-block;">
            <%= button_to "-1", trip_supplies_decrease_path(supply), :class => "quantity", method: :put %>
          </div>
          </td>
        </tr>
      <% end %>
    </table>
<%= form_for @trip do |f| %>
  <%= f.fields_for :supplies, @trip.supplies.build do |supplies_fields| %><br>
    <%= supplies_fields.label "Supply Name" %>
    <%= supplies_fields.text_field :name %>
  <% end %>
  <%= f.submit "Add Supply" %><br><br>
<% end %>
</div>
<div class="container col-md-4">
  <div class="row">
    <a href="#" class="js-next btn btn-primary"  data-trip="<%= @trip.id %>" data-user="<%= @trip.user_id %>">Preview the Next Trip</a>
    <h2 class="titleName"></h2>
    <p class="tripDescription"></p>
    <span class="tripLink"></span>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-md-6">
  <h2>Find a new adventure</h2>
  <%= form_tag("trips/results", method: "post") do %>
    <%= label_tag("Park Name") %>
    <%= text_field_tag(:pname) %>
    <%= submit_tag("Search", :class => "btn btn-primary") %>
  <% end %>
</div>

<div class="col-md-6">
  <button data-user="<%= current_user.id %>" class="upcoming-trips btn btn-primary">See Upcoming Trips</button>
    <table class="table table-striped"></table>
</div>